services:
  - type: web
    name: prezzy-session
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: prezzy-auth
      mountPath: /opt/render/project/src/prezzy_auth
      sizeGB: 1
